# **1.2 PROCEDURE**

In [1]:
import tensorflow as tf

print(tf.config.list_physical_devices('GPU'))
# [PhysicalDevice(name='/physical_device:GPU:0', device_type='GPU')]

print(tf.test.is_built_with_cuda)
# <function is_built_with_cuda at 0x7f4f5730fbf8>

print(tf.test.gpu_device_name())
# /device:GPU:0

print(tf.config.get_visible_devices())
# [PhysicalDevice(name='/physical_device:CPU:0', device_type='CPU'), PhysicalDevice(name='/physical_device:GPU:0', device_type='GPU')]

[PhysicalDevice(name='/physical_device:GPU:0', device_type='GPU')]
<function is_built_with_cuda at 0x000002A132595F70>
/device:GPU:0
[PhysicalDevice(name='/physical_device:CPU:0', device_type='CPU'), PhysicalDevice(name='/physical_device:GPU:0', device_type='GPU')]


In [2]:
const_a = tf.constant([[1, 2, 3, 4]],shape=[2,2], dtype=tf.float32) #Create a 2x2 matrix with values 1, 2, 3, and 4.
const_a

<tf.Tensor: shape=(2, 2), dtype=float32, numpy=
array([[1., 2.],
       [3., 4.]], dtype=float32)>

In [3]:
#View common attributes.
print("value of the constant const_a:", const_a.numpy())
print("data type of the constant const_a:", const_a.dtype)
print("shape of the constant const_a:", const_a.shape)
print("name of the device that is to generate the constant const_a:", const_a.device)

value of the constant const_a: [[1. 2.]
 [3. 4.]]
data type of the constant const_a: <dtype: 'float32'>
shape of the constant const_a: (2, 2)
name of the device that is to generate the constant const_a: /job:localhost/replica:0/task:0/device:GPU:0


In [4]:
zeros_b = tf.zeros(shape=[2, 3], dtype=tf.int32)   #Create a 2x3 matrix with all values being 0.
zeros_b

<tf.Tensor: shape=(2, 3), dtype=int32, numpy=
array([[0, 0, 0],
       [0, 0, 0]])>

In [5]:
zeros_like_c = tf.zeros_like(const_a) #View generated data.
zeros_like_c.numpy()

array([[0., 0.],
       [0., 0.]], dtype=float32)

In [6]:
fill_d = tf.fill([3,3], 8) #2x3 matrix. The element value is 8. #View the data.
fill_d.numpy()

array([[8, 8, 8],
       [8, 8, 8],
       [8, 8, 8]])

In [7]:
random_e = tf.random.normal([5,5],mean=0,stddev=1.0, seed = 1) #View created data.
random_e.numpy()

array([[-0.8113182 ,  1.4845989 ,  0.06532937, -2.4427042 ,  0.0992484 ],
       [ 0.5912243 ,  0.59282297, -2.1229296 , -0.72289723, -0.05627037],
       [ 0.6435448 , -0.26432407,  1.8566332 ,  0.5678417 , -0.3828359 ],
       [-1.4853433 ,  1.2617711 , -0.02530608, -0.2646297 ,  1.5328138 ],
       [-1.7429771 , -0.4378929 , -0.56601   ,  0.32066926,  1.132831  ]],
      dtype=float32)

In [8]:
#Create a list.
list_f = [1,2,3,4,5,6]

#View the data type.
type(list_f)

list

In [9]:
tensor_f = tf.convert_to_tensor(list_f, dtype=tf.float32)
tensor_f

<tf.Tensor: shape=(6,), dtype=float32, numpy=array([1., 2., 3., 4., 5., 6.], dtype=float32)>

In [10]:
#Create a variable. Only the initial value needs to be provided.
var_1 = tf.Variable(tf.ones([2,3]))
var_1

<tf.Variable 'Variable:0' shape=(2, 3) dtype=float32, numpy=
array([[1., 1., 1.],
       [1., 1., 1.]], dtype=float32)>

In [11]:
#Read the variable value.
print("Value of the variable var_1:",var_1.read_value())

#Assign a variable value.
var_value_1=[[1,2,3],[4,5,6]]
var_1.assign(var_value_1)
print("Value of the variable var_1 after the assignment:",var_1.read_value())

Value of the variable var_1: tf.Tensor(
[[1. 1. 1.]
 [1. 1. 1.]], shape=(2, 3), dtype=float32)
Value of the variable var_1 after the assignment: tf.Tensor(
[[1. 2. 3.]
 [4. 5. 6.]], shape=(2, 3), dtype=float32)


In [12]:
#Variable addition
var_1.assign_add(tf.ones([2,3]))
var_1

<tf.Variable 'Variable:0' shape=(2, 3) dtype=float32, numpy=
array([[2., 3., 4.],
       [5., 6., 7.]], dtype=float32)>

In [13]:
#Create a 4-dimensional tensor. The tensor contains four images. The size of each image is 100 x 100 x 3.
tensor_h = tf.random.normal([4,100,100,3])
tensor_h

<tf.Tensor: shape=(4, 100, 100, 3), dtype=float32, numpy=
array([[[[-1.70930135e+00, -4.49918061e-02, -1.58903217e+00],
         [ 3.12792771e-02,  2.17144251e+00, -2.62376189e+00],
         [ 1.08832431e+00, -1.21833399e-01, -3.34820181e-01],
         ...,
         [ 2.54986525e-01, -2.06253398e-02, -4.48896229e-01],
         [ 1.17051923e+00,  6.14995062e-01, -2.78890040e-03],
         [ 2.07062078e+00,  2.72161037e-01, -2.14600325e+00]],

        [[ 5.59184968e-01, -1.99044907e+00,  8.71416390e-01],
         [ 1.91730335e-02, -8.32339466e-01,  1.64546180e+00],
         [-1.12154019e+00, -9.41377997e-01,  6.70729637e-01],
         ...,
         [-2.87934184e-01, -8.55423093e-01,  1.09883618e+00],
         [ 1.28498042e+00, -1.32767618e+00,  1.23782849e+00],
         [ 1.12714517e+00, -1.14500356e+00, -1.25173151e+00]],

        [[-1.02668419e-01, -6.69009089e-01, -8.82090211e-01],
         [ 4.89823222e-02, -5.13644338e-01,  1.59072787e-01],
         [ 1.50328517e-01, -1.35522461e+00

In [14]:
#Extract the first image.
tensor_h[0,:,:,:]

<tf.Tensor: shape=(100, 100, 3), dtype=float32, numpy=
array([[[-1.7093014 , -0.04499181, -1.5890322 ],
        [ 0.03127928,  2.1714425 , -2.623762  ],
        [ 1.0883243 , -0.1218334 , -0.33482018],
        ...,
        [ 0.25498652, -0.02062534, -0.44889623],
        [ 1.1705192 ,  0.61499506, -0.0027889 ],
        [ 2.0706208 ,  0.27216104, -2.1460032 ]],

       [[ 0.55918497, -1.9904491 ,  0.8714164 ],
        [ 0.01917303, -0.83233947,  1.6454618 ],
        [-1.1215402 , -0.941378  ,  0.67072964],
        ...,
        [-0.28793418, -0.8554231 ,  1.0988362 ],
        [ 1.2849804 , -1.3276762 ,  1.2378285 ],
        [ 1.1271452 , -1.1450036 , -1.2517315 ]],

       [[-0.10266842, -0.6690091 , -0.8820902 ],
        [ 0.04898232, -0.51364434,  0.15907279],
        [ 0.15032852, -1.3552246 ,  0.08614599],
        ...,
        [-1.1400967 , -1.3384835 , -0.3751197 ],
        [-0.43153924,  1.5209857 ,  1.2040008 ],
        [ 0.33781588, -0.57136387, -0.13344198]],

       ...,

     

In [15]:
#Extract one slice at an interval of two images.
tensor_h[::2,...]

<tf.Tensor: shape=(2, 100, 100, 3), dtype=float32, numpy=
array([[[[-1.7093014 , -0.04499181, -1.5890322 ],
         [ 0.03127928,  2.1714425 , -2.623762  ],
         [ 1.0883243 , -0.1218334 , -0.33482018],
         ...,
         [ 0.25498652, -0.02062534, -0.44889623],
         [ 1.1705192 ,  0.61499506, -0.0027889 ],
         [ 2.0706208 ,  0.27216104, -2.1460032 ]],

        [[ 0.55918497, -1.9904491 ,  0.8714164 ],
         [ 0.01917303, -0.83233947,  1.6454618 ],
         [-1.1215402 , -0.941378  ,  0.67072964],
         ...,
         [-0.28793418, -0.8554231 ,  1.0988362 ],
         [ 1.2849804 , -1.3276762 ,  1.2378285 ],
         [ 1.1271452 , -1.1450036 , -1.2517315 ]],

        [[-0.10266842, -0.6690091 , -0.8820902 ],
         [ 0.04898232, -0.51364434,  0.15907279],
         [ 0.15032852, -1.3552246 ,  0.08614599],
         ...,
         [-1.1400967 , -1.3384835 , -0.3751197 ],
         [-0.43153924,  1.5209857 ,  1.2040008 ],
         [ 0.33781588, -0.57136387, -0.1334419

In [16]:
#Slice data from the last element.
tensor_h[::-1]

<tf.Tensor: shape=(4, 100, 100, 3), dtype=float32, numpy=
array([[[[ 8.06004584e-01,  3.51013213e-01, -7.43508041e-01],
         [-1.88535690e+00, -5.76852202e-01, -7.21006632e-01],
         [ 3.08038384e-01, -1.40733004e+00,  3.36514354e-01],
         ...,
         [ 9.84766245e-01,  1.77316403e+00,  1.46486759e-01],
         [ 8.23367834e-01, -6.80106819e-01,  9.08959746e-01],
         [-3.01967651e-01,  7.68677950e-01, -1.30150878e+00]],

        [[ 6.99271441e-01, -1.68843722e+00, -1.16908813e+00],
         [-6.75371647e-01,  9.99369398e-02,  1.67251334e-01],
         [-1.30121037e-01,  1.90715611e+00, -1.30874240e+00],
         ...,
         [ 5.94998479e-01, -1.43332517e+00, -9.72964019e-02],
         [ 1.89400747e-01,  1.04823971e+00,  7.94802248e-01],
         [-8.46201777e-01, -3.28234918e-02,  1.22993827e+00]],

        [[ 4.26873535e-01, -1.32984281e+00,  1.28083396e+00],
         [ 4.44405109e-01, -1.87218904e+00,  5.51761091e-01],
         [ 2.04190540e+00, -2.83061326e-01

In [17]:
#Obtain the pixel in the position [20,40] in the second channel of the first image.
tensor_h[0][19][39][1]

<tf.Tensor: shape=(), dtype=float32, numpy=0.31445485>

In [18]:
#Extract the first, second, and fourth images from tensor_h ([4,100,100,3]).
indices = [0,1,3]
tf.gather(tensor_h,axis=0,indices=indices,batch_dims=1)

<tf.Tensor: shape=(3, 100, 100, 3), dtype=float32, numpy=
array([[[[-1.70930135e+00, -4.49918061e-02, -1.58903217e+00],
         [ 3.12792771e-02,  2.17144251e+00, -2.62376189e+00],
         [ 1.08832431e+00, -1.21833399e-01, -3.34820181e-01],
         ...,
         [ 2.54986525e-01, -2.06253398e-02, -4.48896229e-01],
         [ 1.17051923e+00,  6.14995062e-01, -2.78890040e-03],
         [ 2.07062078e+00,  2.72161037e-01, -2.14600325e+00]],

        [[ 5.59184968e-01, -1.99044907e+00,  8.71416390e-01],
         [ 1.91730335e-02, -8.32339466e-01,  1.64546180e+00],
         [-1.12154019e+00, -9.41377997e-01,  6.70729637e-01],
         ...,
         [-2.87934184e-01, -8.55423093e-01,  1.09883618e+00],
         [ 1.28498042e+00, -1.32767618e+00,  1.23782849e+00],
         [ 1.12714517e+00, -1.14500356e+00, -1.25173151e+00]],

        [[-1.02668419e-01, -6.69009089e-01, -8.82090211e-01],
         [ 4.89823222e-02, -5.13644338e-01,  1.59072787e-01],
         [ 1.50328517e-01, -1.35522461e+00

In [19]:
#Extract the pixel in [1,1] from the first dimension of the first image and the pixel in [2,2] from the first dimension of the second image in tensot_h ([4,100,100,3]).
indices = [[0,1,1,0],[1,2,2,0]]
tf.gather_nd(tensor_h,indices=indices)

<tf.Tensor: shape=(2,), dtype=float32, numpy=array([0.01917303, 1.8315349 ], dtype=float32)>

In [20]:
const_d_1 = tf.constant([[1, 2, 3, 4]],shape=[2,2], dtype=tf.float32)

#Three common methods for viewing a dimension:
print(const_d_1.shape)
print(const_d_1.get_shape())
print(tf.shape(const_d_1))
print(tf.shape(const_d_1)) #The output is a tensor. The value of the tensor indicates the size of the tensor dimension to be viewed.

(2, 2)
(2, 2)
tf.Tensor([2 2], shape=(2,), dtype=int32)
tf.Tensor([2 2], shape=(2,), dtype=int32)


In [21]:
reshape_1 = tf.constant([[1,2,3],[4,5,6]])
print(reshape_1)
tf.reshape(reshape_1, (3,2))

tf.Tensor(
[[1 2 3]
 [4 5 6]], shape=(2, 3), dtype=int32)


<tf.Tensor: shape=(3, 2), dtype=int32, numpy=
array([[1, 2],
       [3, 4],
       [5, 6]])>

In [22]:
#Generate a 100 x 100 x 3 tensor to represent a 100 x 100 three-channel color image.
expand_sample_1 = tf.random.normal([100,100,3], seed=1)
print("size of the original data:",expand_sample_1.shape)
print("add a dimension before the first dimension (axis=0): ",tf.expand_dims(expand_sample_1, axis=0).shape)
print("add a dimension before the second dimension (axis=1): ",tf.expand_dims(expand_sample_1, axis=1).shape)
print("add a dimension after the last dimension (axis=-1): ",tf.expand_dims(expand_sample_1, axis=-1).shape)

size of the original data: (100, 100, 3)
add a dimension before the first dimension (axis=0):  (1, 100, 100, 3)
add a dimension before the second dimension (axis=1):  (100, 1, 100, 3)
add a dimension after the last dimension (axis=-1):  (100, 100, 3, 1)


In [23]:
#Generate a 100 x 100 x 3 tensor to represent a 100 x 100 three-channel color image.
squeeze_sample_1 = tf.random.normal([1,100,100,3])
print("size of the original data:",squeeze_sample_1.shape)
squeezed_sample_1 = tf.squeeze(expand_sample_1)
print("data size after dimension squeezing:",squeezed_sample_1.shape)

size of the original data: (1, 100, 100, 3)
data size after dimension squeezing: (100, 100, 3)


In [24]:
#The transposition problem of the low dimension is simple. The input needs to be called by transposing tensors.
tf.transpose
trans_sample_1 = tf.constant([1,2,3,4,5,6],shape=[2,3])
print("size of the original data:",trans_sample_1.shape)
transposed_sample_1 = tf.transpose(trans_sample_1)
print("size of transposed data:",transposed_sample_1.shape)

size of the original data: (2, 3)
size of transposed data: (3, 2)


In [25]:
#perm is required for high-dimensional data transposition, and indicates the dimension sequence of the input tensor. The original dimension sequence of a three-dimensional tensor is [0, 1, 2] (perm), indicating the length, width, and height of high-dimensional data, respectively.Deep Learning Lab Guide-Teacher Version Page 12 Data dimensions can be transposed by changing the sequence of values in perm.
#Generate an $ x 100 x 200 x 3 tensor to represent four 100 x 200 three-channel color images.
trans_sample_2 = tf.random.normal([4,100,200,3])
print("size of the original data:",trans_sample_2.shape)

#Exchange the length and width for the four images. The original perm value is [0,1,2,3], and the new perm value is [0,2,1,3].
transposed_sample_2 = tf.transpose(trans_sample_2,[0,2,1,3])
print("size of transposed data:",transposed_sample_2.shape)

size of the original data: (4, 100, 200, 3)
size of transposed data: (4, 200, 100, 3)


In [26]:
broadcast_sample_1 = tf.constant([1,2,3,4,5,6])
print("original data:",broadcast_sample_1.numpy())
broadcasted_sample_1 = tf.broadcast_to(broadcast_sample_1,shape=[4,6])
print("broadcasted data:",broadcasted_sample_1.numpy())

original data: [1 2 3 4 5 6]
broadcasted data: [[1 2 3 4 5 6]
 [1 2 3 4 5 6]
 [1 2 3 4 5 6]
 [1 2 3 4 5 6]]


In [27]:
#During the operation, if two arrays have different shapes, TensorFlow automatically triggers the broadcast mechanism as NumPy does.
a = tf.constant([[ 0, 0, 0], [10,10,10], [20,20,20], [30,30,30]])
b = tf.constant([1,2,3])
print(a + b)

tf.Tensor(
[[ 1  2  3]
 [11 12 13]
 [21 22 23]
 [31 32 33]], shape=(4, 3), dtype=int32)


In [28]:
a = tf.constant([[3, 5], [4, 8]])
b = tf.constant([[1, 6], [2, 9]])
print(tf.add(a, b))

tf.Tensor(
[[ 4 11]
 [ 6 17]], shape=(2, 2), dtype=int32)


In [29]:
tf.matmul(a,b)

<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[13, 63],
       [20, 96]])>

In [30]:
argmax_sample_1 = tf.constant([[1,3,2],[2,5,8],[7,5,9]])
print("input tensor:",argmax_sample_1.numpy())
max_sample_1 = tf.argmax(argmax_sample_1, axis=0)
max_sample_2 = tf.argmax(argmax_sample_1, axis=1)
print("locate the maximum value by column:",max_sample_1.numpy())
print("locate the maximum value by row:",max_sample_2.numpy())

input tensor: [[1 3 2]
 [2 5 8]
 [7 5 9]]
locate the maximum value by column: [2 1 2]
locate the maximum value by row: [1 2 2]


In [31]:
reduce_sample_1 = tf.constant([1,2,3,4,5,6],shape=[2,3])
print("original data",reduce_sample_1.numpy())
print("calculate the sum of all elements in the tensor (axis=None):",tf.reduce_sum(reduce_sample_1,axis=None).numpy())
print("calculate the sum of elements in each column by column (axis=0):",tf.reduce_sum(reduce_sample_1,axis=0).numpy())
print("calculate the sum of elements in each column by row (axis=1):",tf.reduce_sum(reduce_sample_1,axis=1).numpy())

original data [[1 2 3]
 [4 5 6]]
calculate the sum of all elements in the tensor (axis=None): 21
calculate the sum of elements in each column by column (axis=0): [5 7 9]
calculate the sum of elements in each column by row (axis=1): [ 6 15]


In [32]:
concat_sample_1 = tf.random.normal([4,100,100,3])
concat_sample_2 = tf.random.normal([40,100,100,3])
print("sizes of original data: ",concat_sample_1.shape, concat_sample_2.shape)
concated_sample_1 = tf.concat([concat_sample_1,concat_sample_2],axis=0)
print("size of the concatenated data:",concated_sample_1.shape)

sizes of original data:  (4, 100, 100, 3) (40, 100, 100, 3)
size of the concatenated data: (44, 100, 100, 3)


In [33]:
stack_sample_1 = tf.random.normal([100,100,3])
stack_sample_2 = tf.random.normal([100,100,3])
print("sizes of original data: ",stack_sample_1.shape, stack_sample_2.shape)

#Dimensions increase after the concatenation. If axis is set to 0, a dimension is added before the first dimension.
stacked_sample_1 = tf.stack([stack_sample_1, stack_sample_2],axis=0)
print("size of the concatenated data:",stacked_sample_1.shape)

sizes of original data:  (100, 100, 3) (100, 100, 3)
size of the concatenated data: (2, 100, 100, 3)


In [34]:
#Split data based on the first dimension and output the split data in a list.
tf.unstack(stacked_sample_1,axis=0)

[<tf.Tensor: shape=(100, 100, 3), dtype=float32, numpy=
 array([[[-0.03299728, -0.1775733 ,  0.25025854],
         [ 0.50594115,  0.02866779, -0.2389727 ],
         [-1.7778921 , -0.37175632,  0.29791516],
         ...,
         [ 0.04447179,  1.0483598 ,  1.2940078 ],
         [ 0.5280574 ,  0.27182984, -0.49930203],
         [-0.39468908,  1.283789  , -1.4101322 ]],
 
        [[-0.11600413, -0.78924435, -0.8406448 ],
         [-1.3690124 , -1.7435253 , -0.7023674 ],
         [-1.1477895 ,  0.2786808 , -0.90994096],
         ...,
         [-0.52972406, -1.904917  , -0.24199174],
         [ 0.6177599 , -1.3840274 ,  1.9006202 ],
         [-0.6254984 , -2.0439138 , -1.0701884 ]],
 
        [[-0.18974133,  1.093628  ,  1.0882305 ],
         [-0.99843556,  0.5457577 ,  0.9167265 ],
         [-1.1324621 , -1.0126121 , -0.19320475],
         ...,
         [-1.1459612 ,  1.9901415 , -0.8263735 ],
         [ 0.69589025, -1.7395126 ,  1.6910956 ],
         [ 0.06461692, -1.9591635 ,  0.6231125

In [35]:
import numpy as np

split_sample_1 = tf.random.normal([10,100,100,3])
print("size of the original data:",split_sample_1.shape)

splited_sample_1 = tf.split(split_sample_1, num_or_size_splits=5,axis=0)
print("size of the split data when m_or_size_splits is set to 10: ",np.shape(splited_sample_1))

splited_sample_2 = tf.split(split_sample_1, num_or_size_splits=[3,5,2],axis=0)
print("When num_or_size_splits=[3,5,2], the size of the split data is:", np.shape(splited_sample_2[0]),

np.shape(splited_sample_2[1]), np.shape(splited_sample_2[2]))

size of the original data: (10, 100, 100, 3)
size of the split data when m_or_size_splits is set to 10:  (5, 2, 100, 100, 3)
When num_or_size_splits=[3,5,2], the size of the split data is: (3, 100, 100, 3) (5, 100, 100, 3) (2, 100, 100, 3)


In [36]:
sort_sample_1 = tf.random.shuffle(tf.range(10))
print("input tensor:",sort_sample_1.numpy())

sorted_sample_1 = tf.sort(sort_sample_1, direction="ASCENDING")
print("tensor sorted in ascending order:",sorted_sample_1.numpy())

sorted_sample_2 = tf.argsort(sort_sample_1,direction="ASCENDING")
print("indexes of elements of the tensors in ascending order:",sorted_sample_2.numpy())

input tensor: [3 4 1 2 6 7 8 0 9 5]
tensor sorted in ascending order: [0 1 2 3 4 5 6 7 8 9]
indexes of elements of the tensors in ascending order: [7 2 3 0 1 9 4 5 6 8]


In [37]:
values, index = tf.nn.top_k(sort_sample_1,5)
print("input tensor:",sort_sample_1.numpy())
print("first five values in ascending order:", values.numpy())
print("indexes of the first five values in ascending order:", index.numpy())

input tensor: [3 4 1 2 6 7 8 0 9 5]
first five values in ascending order: [9 8 7 6 5]
indexes of the first five values in ascending order: [8 6 5 4 9]


In [38]:
x = tf.ones((2, 2), dtype=tf.dtypes.float32)
y = tf.constant([[1, 2], [3, 4]], dtype=tf.dtypes.float32)
z = tf.matmul(x, y)
print(z)

tf.Tensor(
[[4. 6.]
 [4. 6.]], shape=(2, 2), dtype=float32)


In [39]:
#Use the syntax of TensorFlow 1.x in TensorFlow 2. You can install the v1 compatibility package in TensorFlow 2.0 to inherit the TensorFlow 1.x code and disable the eager execution mode.
import tensorflow.compat.v1 as tf
tf.disable_eager_execution()

#Create a graph and define it as a computational graph.
a = tf.ones((2, 2), dtype=tf.dtypes.float32)
b = tf.constant([[1, 2], [3, 4]], dtype=tf.dtypes.float32)
c = tf.matmul(a, b)

#Enable the drawing function, and perform the multiplication operation to obtain data.
with tf.Session() as sess:
   print(sess.run(c))

[[4. 6.]
 [4. 6.]]


In [40]:
import tensorflow as tf

thre_1 = tf.random.uniform([], 0, 1)
x = tf.reshape(tf.range(0, 4), [2, 2])
print(thre_1)
if thre_1.numpy() > 0.5:
   y = tf.matmul(x, x)
else:
   y = tf.add(x, x)

Tensor("random_uniform/RandomUniform:0", shape=(), dtype=float32)


AttributeError: 'Tensor' object has no attribute 'numpy'

In [ ]:
@tf.function
def simple_nn_layer(w,x,b):
   print(b)
   return tf.nn.relu(tf.matmul(w, x)+b)
w = tf.random.uniform((3, 3))
x = tf.random.uniform((3, 3))
b = tf.constant(0.5, dtype='float32')
simple_nn_layer(w,x,b)

Tensor("b:0", shape=(), dtype=float32)


<tf.Tensor 'PartitionedCall:0' shape=(3, 3) dtype=float32>

In [ ]:
#Use the timeit module to measure the execution time of a small code segment.
import timeit

#Create a convolutional layer.
CNN_cell = tf.keras.layers.Conv2D(filters=100,kernel_size=2,strides=(1,1))

#Use @tf.function to convert the operation into a graph.
@tf.function
def CNN_fn(image):
   return CNN_cell(image)
image = tf.zeros([100, 200, 200, 3])

#Compare the execution time of the two modes.
CNN_cell(image)
CNN_fn(image)

#Call timeit.timeit to measure the time required for executing the code 10 times.
print("time required for performing the computation of one convolutional neural network (CNN) layer in eager execution mode:", timeit.timeit(lambda: CNN_cell(image), number=10))
print("time required for performing the computation of one CNN layer in graph mode:", timeit.timeit(lambda: CNN_fn(image), number=10))

time required for performing the computation of one convolutional neural network (CNN) layer in eager execution mode: 0.021845400000000126
time required for performing the computation of one CNN layer in graph mode: 0.009503900000002119
