# **2.2 PROCEDURE**

In [16]:
import tensorflow.keras.layers as layers
import tensorflow as tf

model = tf.keras.Sequential()
model.add(layers.Dense(32, activation='relu'))
model.add(layers.Dense(32, activation='relu'))
model.add(layers.Dense(10, activation='softmax'))

#Use the output of the previous layer as the input of the next layer.
x = tf.keras.Input(shape=(32,))
h1 = layers.Dense(32, activation='relu')(x)
h2 = layers.Dense(32, activation='relu')(h1)
y = layers.Dense(10, activation='softmax')(h2)
model_sample_2 = tf.keras.models.Model(x, y)

#Print model information.
model_sample_2.summary()

Model: "model_4"
_________________________________________________________________
 Layer (type)                Output Shape              Param #   
 input_5 (InputLayer)        [(None, 32)]              0         
                                                                 
 dense_12 (Dense)            (None, 32)                1056      
                                                                 
 dense_13 (Dense)            (None, 32)                1056      
                                                                 
 dense_14 (Dense)            (None, 10)                330       
                                                                 
Total params: 2,442
Trainable params: 2,442
Non-trainable params: 0
_________________________________________________________________


In [17]:
#Create a fully connected layer that contains 32 neurons. Set the activation function to sigmoid.
#The activation parameter can be set to a function name string, for example, sigmoid or a function object, for example, tf.sigmoid. layers.Dense(32, activation='sigmoid') layers.Dense(32, activation=tf.sigmoid)

#Set kernel_initializer
layers.Dense(32, kernel_initializer=tf.keras.initializers.he_normal)

#Set kernel_regularizer to L2 regularization
layers.Dense(32, kernel_regularizer=tf.keras.regularizers.l2(0.01))

In [18]:
layers.Conv2D(64,[1,1],2,padding='same',activation="relu")

In [19]:
layers.MaxPooling2D(pool_size=(2,2),strides=(2,1))

In [20]:
import numpy as np

inputs = tf.keras.Input(shape=(3, 1))
lstm = layers.LSTM(1, return_sequences=True)(inputs)
model_lstm_1 = tf.keras.models.Model(inputs=inputs, outputs=lstm)
inputs = tf.keras.Input(shape=(3, 1))
lstm = layers.LSTM(1, return_sequences=False)(inputs)
model_lstm_2 = tf.keras.models.Model(inputs=inputs, outputs=lstm)

#Sequences t1, t2, and t3
data = [[[0.1], 
         [0.2], 
         [0.3]]]

print(data)
print("output when return_sequences is set to True",model_lstm_1.predict(data))
print("output when return_sequences is set to False",model_lstm_2.predict(data))

[[[0.1], [0.2], [0.3]]]
1/1 [==============================] - 0s 403ms/step
output when return_sequences is set to True [[[-0.00352525]
  [-0.0088949 ]
  [-0.01491457]]]
1/1 [==============================] - 0s 348ms/step
output when return_sequences is set to False [[0.00736878]]


In [21]:
tf.keras.layers.LSTM(16, return_sequences=True)

#LSTMCell
x = tf.keras.Input((None, 3))
y = layers.RNN(layers.LSTMCell(16))(x)
model_lstm_3= tf.keras.Model(x, y)
model = tf.keras.Sequential()
model.add(layers.Dense(10, activation='softmax'))

In [22]:
#Determine the optimizer (optimizer), loss function (loss), and model evaluation method (metrics).
model.compile(optimizer=tf.keras.optimizers.Adam(0.001),
              loss=tf.keras.losses.categorical_crossentropy,
              metrics=[tf.keras.metrics.categorical_accuracy])

In [23]:
import numpy as np

train_x = np.random.random((1000, 36))
train_y = np.random.random((1000, 10))
val_x = np.random.random((200, 36))
val_y = np.random.random((200, 10))
model.fit(train_x, train_y, epochs=10, batch_size=100,
          validation_data=(val_x, val_y))

Epoch 1/10
10/10 [==============================] - 1s 22ms/step - loss: 12.1642 - categorical_accuracy: 0.0880 - val_loss: 12.0438 - val_categorical_accuracy: 0.0950
Epoch 2/10
10/10 [==============================] - 0s 7ms/step - loss: 12.1631 - categorical_accuracy: 0.0880 - val_loss: 12.0429 - val_categorical_accuracy: 0.0950
Epoch 3/10
10/10 [==============================] - 0s 14ms/step - loss: 12.1630 - categorical_accuracy: 0.0880 - val_loss: 12.0430 - val_categorical_accuracy: 0.0950
Epoch 4/10
10/10 [==============================] - 0s 7ms/step - loss: 12.1625 - categorical_accuracy: 0.0870 - val_loss: 12.0422 - val_categorical_accuracy: 0.0950
Epoch 5/10
10/10 [==============================] - 0s 7ms/step - loss: 12.1619 - categorical_accuracy: 0.0870 - val_loss: 12.0414 - val_categorical_accuracy: 0.0950
Epoch 6/10
10/10 [==============================] - 0s 7ms/step - loss: 12.1616 - categorical_accuracy: 0.0870 - val_loss: 12.0417 - val_categorical_accuracy: 0.0950
Ep

In [24]:
dataset = tf.data.Dataset.from_tensor_slices((train_x, train_y))
dataset = dataset.batch(32)
dataset = dataset.repeat()
val_dataset = tf.data.Dataset.from_tensor_slices((val_x, val_y))
val_dataset = val_dataset.batch(32)
val_dataset = val_dataset.repeat()
model.fit(dataset, epochs=10, steps_per_epoch=30,
          validation_data=val_dataset, validation_steps=3)

Epoch 1/10


30/30 [==============================] - 0s 8ms/step - loss: 12.1350 - categorical_accuracy: 0.0896 - val_loss: 11.8892 - val_categorical_accuracy: 0.0938
Epoch 2/10
30/30 [==============================] - 0s 5ms/step - loss: 12.1537 - categorical_accuracy: 0.0919 - val_loss: 11.8889 - val_categorical_accuracy: 0.0938
Epoch 3/10
30/30 [==============================] - 0s 5ms/step - loss: 12.1586 - categorical_accuracy: 0.0865 - val_loss: 11.8879 - val_categorical_accuracy: 0.0938
Epoch 4/10
30/30 [==============================] - 0s 5ms/step - loss: 12.1602 - categorical_accuracy: 0.0865 - val_loss: 11.8863 - val_categorical_accuracy: 0.0938
Epoch 5/10
30/30 [==============================] - 0s 4ms/step - loss: 12.1214 - categorical_accuracy: 0.0887 - val_loss: 11.8845 - val_categorical_accuracy: 0.0938
Epoch 6/10
30/30 [==============================] - 0s 4ms/step - loss: 12.1396 - categorical_accuracy: 0.0908 - val_loss: 11.8830 - val_categorical_accuracy: 0.0938
Epoch 7/10
30/3

In [30]:
#Set hyperparameters.
Epochs = 10
#Define a function for dynamically setting the learning rate.
def lr_Scheduler(epoch):
   if epoch > 0.9 * Epochs:
      lr = 0.0001
   elif epoch > 0.5 * Epochs:
      lr = 0.001
   elif epoch > 0.25 * Epochs:
      lr = 0.01
   else:
      lr = 0.1
   
   print(lr)
   return lr

callbacks = [
#Early stopping:
   tf.keras.callbacks.EarlyStopping(
#Metric for determining whether the model performance has no further improvement
   monitor='val_loss',
#Threshold for determining whether the model performance has no further improvement
   min_delta=1e-2,
#Number of epochs in which the model performance has no further improvement
   patience=2),
#Periodically save models.
   tf.keras.callbacks.ModelCheckpoint(
#Model path
   filepath='testmodel_{epoch}.h5',
#Whether to save the optimal model.
   save_best_only=True,
#Monitored metric
   monitor='val_loss'),
#Dynamically change the learning rate.
   tf.keras.callbacks.LearningRateScheduler(lr_Scheduler),
#Use TensorBoard.
   tf.keras.callbacks.TensorBoard(log_dir='./logs')
]

model.fit(train_x, train_y, batch_size=16, epochs=Epochs,
callbacks=callbacks, validation_data=(val_x, val_y))

0.1
Epoch 1/10
63/63 [==============================] - 1s 9ms/step - loss: 12.4010 - categorical_accuracy: 0.0930 - val_loss: 12.1581 - val_categorical_accuracy: 0.0900 - lr: 0.1000
0.1
Epoch 2/10
63/63 [==============================] - 1s 8ms/step - loss: 12.4910 - categorical_accuracy: 0.0900 - val_loss: 12.3064 - val_categorical_accuracy: 0.0900 - lr: 0.1000
0.1
Epoch 3/10
63/63 [==============================] - 1s 9ms/step - loss: 12.4218 - categorical_accuracy: 0.0920 - val_loss: 12.0491 - val_categorical_accuracy: 0.1050 - lr: 0.1000
0.01
Epoch 4/10
63/63 [==============================] - 0s 7ms/step - loss: 12.1079 - categorical_accuracy: 0.0890 - val_loss: 12.0334 - val_categorical_accuracy: 0.1150 - lr: 0.0100
0.01
Epoch 5/10
63/63 [==============================] - 1s 9ms/step - loss: 12.1342 - categorical_accuracy: 0.0920 - val_loss: 11.9379 - val_categorical_accuracy: 0.0950 - lr: 0.0100
0.01
Epoch 6/10
63/63 [==============================] - 1s 9ms/step - loss: 12.120

In [26]:
#Model evaluation
test_x = np.random.random((1000, 36))
test_y = np.random.random((1000, 10))
model.evaluate(test_x, test_y, batch_size=32)

32/32 [==============================] - 0s 4ms/step - loss: 12.3695 - categorical_accuracy: 0.1220


[12.369544982910156, 0.12200000137090683]

In [27]:
#Model prediction
pre_x = np.random.random((10, 36))
result = model.predict(test_x,)
print(result)

32/32 [==============================] - 0s 1ms/step
[[0.06471244 0.06549323 0.09057109 ... 0.11202481 0.02795932 0.08894405]
 [0.07243478 0.07211496 0.11079419 ... 0.2119318  0.02814083 0.08649752]
 [0.08891644 0.05908849 0.14934845 ... 0.24642192 0.06437134 0.08014077]
 ...
 [0.06288819 0.17370349 0.07604307 ... 0.16760048 0.06406596 0.04978967]
 [0.0921402  0.06780529 0.16550049 ... 0.15973444 0.0262548  0.06238133]
 [0.0523982  0.06769045 0.10962795 ... 0.21516578 0.08620305 0.05055104]]


In [28]:
import numpy as np

#Save models.
model.save('./model/the_save_model.h5')

#Import models.
new_model = tf.keras.models.load_model('./model/the_save_model.h5')
new_prediction = new_model.predict(test_x)

#np.testing.assert_allclose: determines whether the similarity between two objects exceeds the specified tolerance. If yes, the system displays an exception. :
#atol: specified tolerance
np.testing.assert_allclose(result, new_prediction, atol=1e-6) #Prediction results are the same.

32/32 [==============================] - 0s 2ms/step


In [29]:
model.save_weights('./model/model_weights')
model.save_weights('./model/model_weights.h5')

#Load the weights.
model.load_weights('./model/model_weights')
model.load_weights('./model/model_weights.h5')